apiVersion: argoproj.io/v1alpha1                                                                                                                                │
kind: Application
metadata:
  name: jenkins
  namespace: ci-cd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
project: default
source:
  chart: jenkins-app
  repoURL: https://artsiomborisevich.github.io/helm-borisevich/
  targetRevision: 0.2.0
syncPolicy:
  automated:
    prune: true
