apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  destination:
    namespace: ci-cd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: jenkins-app
    helm:
      valueFiles:
      - values.yaml
    repoURL: https://artsiomborisevich.github.io/helm-borisevich/
    targetRevision: 0.3.0
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
