---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-drupal
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: drupal
    helm:
      parameters:
      - name: mariadb.enabled
        value: "false"
      - name: externalDatabase.host
        value: 192.168.201.3
      - name: externalDatabase.existingSecret
        value: argo-secrets-drupal
      - name: externalDatabase.database
        value: drupal
      - name: global.storageClass
        value: nfs
      - name: existingSecret
        value: argo-secrets-drupal
      - name: drupalEmail
        value: artiom.borisevich@idt.net
      - name: ingress.enabled
        value: "true"
      - name: ingress.hostname
        value: drupal-sa.k8s-3.sa
      - name: ingress.apiversion
        value: networking.k8s.io/v1
      - name: ingress.annotations
        value: kubernetes.io/ingress.class: nginx
      - name: ingress.pathType
        value: Prefix
      - name: service.type
        value: LoadBalancer
      valueFiles:
      - values.yaml
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.5.12
  syncPolicy:
    automated:
      prune: true
